name: Android CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: apt
      run: |
        set -x
        sudo apt-get update && sudo apt-get install wget curl  android-sdk
        wget --quiet https://dl.google.com/android/repository/android-ndk-r20-linux-x86_64.zip 
        unzip android-ndk-r20-linux-x86_64.zip > /dev/null
        export ANDROID_NDK_ROOT=`pwd`/android-ndk-r20 
        #export ANDROID_SDK_ROOT=/usr/local/android-sdk 
        export PATH=`pwd`/android-ndk-r20:$PATH       
        
        export APP_PLATFORM=android-24
        
        ndk-build
        
